version: "3.9"

services:
  frontend:
    image: jacktheskunk/app-frontend:null
    # build: ./frontend  # decommenta se vuoi buildare l’immagine localmente
    ports:
      - "80:80"  # porta host 8081 per il frontend





  backend:
    image: jacktheskunk/app-backend:null
    # build: ./backend  # decommenta se vuoi buildare l’immagine localmente
    ports:
      - "5000:5000"

