version: "3.9"

services:
  backend:
    image: jacktheskunk/app-backend
    container_name: lab-backend
    ports:
      - "5000:5000"

  frontend:
    image: jacktheskunk/app-frontend
    container_name: lab-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

